dataloader_args:
  batch_size: 14 #RTX2080 1, V100: 6, A800: 14
  drop_last: true
  num_workers: 6
  pin_memory: true
  prefetch_factor: 6

dataset_args:
  resample_rate: &sr 16000
  sample_num_per_epoch: 0
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  chunk_len: 48000
  noise_prob: 0 # prob to add noise aug per sample
  noise_lmdb_file: './data/musan/lmdb'
  cues:
    visual:
      use: true
      required: true
  cue_processing:
    visual:

enable_amp: false
exp_dir: exp/BSRNN
gpus: '0,1'
log_batch_interval: 100

loss: SISDR
loss_args: { }

# loss: [SISDR, XX]               ### Put SISDR in the first position for validation set
# loss_args:
#   loss_posi: [[0],[1]]
#   loss_weight: [[1.0],[1.0]]

model:
  tse_model: TSE_BSRNN_VISUAL
model_args:
  tse_model:
    separator:
      sr: *sr
      win: 512
      stride: 128
      feature_dim: 128
      num_repeat: 6
      causal: False
      nspk: 1
    visual:
      features:
        muse_visual:
          enabled: True
          vf_pretrained: "/zhangke/junjie/MeMo/src/Model/visual_frontend/visual_frontend.pt"
          vtcn_channels: 512
          vtcn_layers: 5
          upsample: True
          mix_dim: 128
          fusion: "concat"

# find_unused_parameters: True

model_init:
  tse_model: null
  discriminator: null
  spk_model: null

num_avg: 10
num_epochs: 150

optimizer:
  tse_model: Adam
optimizer_args:
  tse_model:
    lr: 0.001  # NOTICE: These args do NOT work! The initial lr is determined in the scheduler_args currently!
    weight_decay: 0.0001

clip_grad: 5.0
save_epoch_interval: 1

scheduler:
  tse_model: ExponentialDecrease
scheduler_args:
  tse_model:
    final_lr: 2.5e-05
    initial_lr: 0.001
    warm_from_zero: false
    warm_up_epoch: 0

seed: 42
